### ISSUE TITLE
`ghc-options` don't end up in test-suite sections

### ISSUE THREAD

**Issue by soenkehahn** [sol/cabalize#2]
From a `package.yaml` file like this:
```
ghc-options: -Wall -fno-warn-name-shadowing

dependencies:
  - base == 4.*
  - generics-sop
  - safe

library: {}

tests:
  spec:
    main: "Spec.hs"
    ghc-options: "-threaded -O0 -pgmL markdown-unlit"
    source-dirs:
      - test
      - examples

    dependencies:
      - getopt-generics
      - hspec
      - hspec-expectations
      - silently
```
I would expect the test-suite section of the generated cabal file to contain a `ghc-options` field with the value `-Wall -fno-warn-name-shadowing -threaded -O0 -pgmL markdown-unlit` but it has none.
